---
- name: "Common ui config"
  block:
    - name: "Clone Splatmoji"
      git:
         repo: "https://github.com/cspeterson/splatmoji"
         dest: "{{home}}/.splatmoji"
    - name: "Install python dependencies"
      pip:
          name: "{{item}}"
          state: latest
          extra_args: "--user"
      when: nixos_file.stat.exists == false
      with_items:
        - "autotiling" # for i3
        - "pyyml" # for kitty-hintsconfig
    - name: "Create some directories"
      file:
         path: "{{home}}/{{item}}"
         state: "directory"
      with_items:
         - ".config/i3/"
         - ".config/polybar/"
         - ".config/kitty/"
         - ".config/dunst/"
         - ".smount/"
    - name: "Remove legacy configs"
      file:
        path: "{{home}}/{{item}}"
        state: "absent"
      with_items:
        - ".compton.conf"
    - name: "Copy defaults"
      copy:
       src:  "{{item.src}}"
       dest : "{{home}}/{{item.dst}}"
       force: no
      with_items:
         - { src : "kitty_default_theme.conf", dst : ".config/kitty/current-theme.conf"}
    - name: "Copy additionnal configuration files"
      copy:
       src:  "{{item.src}}"
       dest : "{{home}}/{{item.dst}}"
      with_items:
         - { src : "i3", dst : ".config/i3/config"}
         - { src : "dunstrc", dst : ".config/dunst/dunstrc"}
         - { src : "compton.conf", dst : ".config/picom.conf"}
         - { src : "kitty.conf", dst : ".config/kitty/kitty.conf"}
         - { src : "polybar.ini", dst : ".config/polybar/config.ini"}
         - { src : "redshift.conf", dst : ".config/redshift.conf"}
         - { src : "xresources", dst : ".Xresources"}
         - { src : "kittyaliases", dst : ".aliases/10kitty"}
      notify: activate xres
    - name: "Clone kitty-hintsconfig from github"
      git:
        repo: "https://github.com/Lqp1/kitty-hintsconfig"
        dest: "{{home}}/.config/kitty/kitty-hintsconfig"
    - name: "Configure GTK-2.0 apps"
      lineinfile:
          create: yes
          line: "gtk-key-theme-name = \"Emacs\""
          path: "{{home}}/.gtkrc-2.0"
    - name: "Configure minimal GTK-3.0 config file"
      lineinfile:
          create: yes
          line: "[Settings]"
          path: "{{home}}/.config/gtk-3.0/settings.ini"
    - name: "Configure GTK-3.0 apps"
      lineinfile:
          line: "gtk-key-theme-name = \"Emacs\""
          insertafter: "[Settings]"
          path: "{{home}}/.config/gtk-3.0/settings.ini"
    - name: "Copy fonts"
      copy:
          src: "res/fonts/"
          dest: "{{home}}/.local/share/fonts/"
    - name: "Copy powerline Noto Mono"
      copy:
          src: "res/powerline-fonts/NotoMono/Noto Mono for Powerline.ttf"
          dest: "{{home}}/.local/share/fonts/"
    - name: "Add kitty TERMINAL variable in profile"
      copy:
          dest: "{{home}}/.profile.d/10kitty"
          content: "export TERMINAL=\"kitty\"\n"
          mode: 0644
    - name: "Add custom polybar script"
      copy:
          src: "polybar-custom.sh"
          dest: "{{home}}/.config/polybar/custom.sh"
          mode: 0500
    - name: "Create autostart script"
      lineinfile:
          create: 'yes'
          insertbefore: "BOF"
          line: "#!/usr/bin/env bash"
          path: "{{home}}/.config/i3/autostart.sh"
          mode: 0500
    - name: "Add autostart programs"
      lineinfile:
          line: "{{item}} &"
          path: "{{home}}/.config/i3/autostart.sh"
          mode: 0500
      with_items: "{{autostart}}"
  when: not minimal|bool
