---
- name: "Common ui config"
  block:
    - stat:
        path: '/etc/NIXOS'
      register: nixos_file
    - name: "Check optional dependencies"
      command: "which {{ item }}"
      with_items:
         - i3
         - feh
         - rofi
         - xdotool
         - polybar
    - name: "Clone Splatmoji"
      git:
         repo: "https://github.com/cspeterson/splatmoji"
         dest: "{{home}}/.splatmoji"
    - name: "Install autotiling from pip"
      pip:
          name: "autotiling"
          state: latest
          extra_args: "--user"
      when: nixos_file.stat.exists == false
    - name: "Create some directories"
      file:
         path: "{{home}}/{{item}}"
         state: "directory"
      with_items:
         - ".config/i3/"
         - ".config/polybar/"
    - name: "Copy additionnal configuration files"
      copy:
       src:  "{{item.src}}"
       dest : "{{home}}/{{item.dst}}"
      with_items:
         - { src : "i3", dst : ".config/i3/config"}
         - { src : "polybar.ini", dst : ".config/polybar/config.ini"}
         - { src : "redshift.conf", dst : ".config/redshift.conf"}
         - { src : "xresources", dst : ".Xresources"}
      notify: activate xres
    - name: "Configure GTK-2.0 apps"
      lineinfile:
          create: yes
          line: "gtk-key-theme-name = \"Emacs\""
          path: "{{home}}/.gtkrc-2.0"
    - name: "Configure minimal GTK-3.0 config file"
      lineinfile:
          create: yes
          line: "[Settings]"
          path: "{{home}}/.config/gtk-3.0/settings.ini"
    - name: "Configure GTK-3.0 apps"
      lineinfile:
          line: "gtk-key-theme-name = \"Emacs\""
          insertafter: "[Settings]"
          path: "{{home}}/.config/gtk-3.0/settings.ini"
    - name: "Copy fonts"
      copy:
          src: "res/fonts/"
          dest: "{{home}}/.local/share/fonts/"
  when: not minimal|bool
