---
- name: "Common ui config"
  block:
    - name: "Setup a simple target for i3 to load graphical-session.target"
      template:
        src: "i3-session.target.j2"
        dest: "~/.config/systemd/user/i3-session.target"
    - name: "Install python dependencies"
      pip:
          name: "{{python_dependencies}}"
          state: latest
          extra_args: "--user"
      when: nixos_file.stat.exists == false
    - name: "Create some directories"
      file:
         path: "{{home}}/{{item}}"
         state: "directory"
      with_items:
         - ".config/i3/"
         - ".config/polybar/"
         - ".config/kitty/"
         - ".config/rofi/"
         - ".config/dunst/"
         - ".config/gtk-3.0/"
         - ".smount/"
         - ".local/share/fonts/fira-code"
    - name: "Remove legacy configs"
      file:
        path: "{{home}}/{{item}}"
        state: "absent"
      with_items:
        - ".compton.conf"
        - "bin/exa-linux-x86_64"
        - ".splatmoji"
        - ".rofimoji"
        - ".config/polybar/custom.sh"
    - name: "Copy defaults"
      copy:
       src:  "{{item.src}}"
       dest : "{{home}}/{{item.dst}}"
       force: no
      with_items:
         - { src : "kitty_default_theme.conf", dst : ".config/kitty/current-theme.conf"}
    - name: "Copy additionnal configuration files"
      copy:
       src:  "{{item.src}}"
       dest : "{{home}}/{{item.dst}}"
      with_items:
         - { src : "i3", dst : ".config/i3/config"}
         - { src : "dunstrc", dst : ".config/dunst/dunstrc"}
         - { src : "compton.conf", dst : ".config/picom.conf"}
         - { src : "kitty.conf", dst : ".config/kitty/kitty.conf"}
         - { src : "kitty-ssh.conf", dst : ".config/kitty/ssh.conf"}
         - { src : "rofi.rasi", dst : ".config/rofi/config.rasi"}
         - { src : "polybar.ini", dst : ".config/polybar/config.ini"}
         - { src : "redshift.conf", dst : ".config/redshift.conf"}
         - { src : "xresources", dst : ".Xresources"}
         - { src : "kittyaliases", dst : ".aliases/10kitty"}
      notify: activate xres
    - name: "Clone kitty-hintsconfig from github"
      git:
        repo: "https://github.com/Lqp1/kitty-hintsconfig"
        dest: "{{home}}/.config/kitty/kitty-hintsconfig"
    - name: "Configure GTK-2.0 apps"
      lineinfile:
          create: yes
          line: "{{item.key}} = {{item.value}}"
          path: "{{home}}/.gtkrc-2.0"
      with_items: "{{gtk_config}}"
    - name: "Configure GTK-3.0 apps"
      ini_file:
          create: yes
          section: "Settings"
          option: "{{item.key}}"
          value: "{{item.value}}"
          path: "{{home}}/.config/gtk-3.0/settings.ini"
      with_items: "{{gtk_config}}"
    - name: "Fetch jira-code font family"
      unarchive:
        remote_src: yes
        src: "https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip"
        dest: "{{home}}/.local/share/fonts/fira-code"
      notify: update fc-cache
    - name: "Fetch other various fonts from internet"
      get_url:
        url: "{{item.src}}"
        dest: "{{home}}/.local/share/fonts/{{item.name}}.ttf"
      notify: update fc-cache
      with_items:
        - src: "https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf"
          name: "NotoColorEmoji"
        - src: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/Regular/complete/Iosevka%20Nerd%20Font%20Complete.ttf"
          name: "Iosevka Nerd Font Complete"
        - src: "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansMono/NotoSansMono-Regular.ttf"
          name: "NotoSansMono-Regular"
    - name: "Add kitty TERMINAL variable in profile"
      copy:
          dest: "{{home}}/.profile.d/10kitty"
          content: "export TERMINAL=\"kitty\"\n"
          mode: 0644
    - name: "Add custom polybar script"
      copy:
          src: "polybar-custom"
          dest: "{{home}}/.config/polybar/custom"
          mode: 0500
    - name: "Create autostart script"
      lineinfile:
          create: 'yes'
          insertbefore: "BOF"
          line: "#!/usr/bin/env bash"
          path: "{{home}}/.config/i3/autostart.sh"
          mode: 0500
    - name: "Add autostart programs"
      lineinfile:
          line: "{{item}} &"
          path: "{{home}}/.config/i3/autostart.sh"
          mode: 0500
      with_items: "{{autostart}}"
  when: not minimal|bool
