#!/usr/bin/env bash

filename='/tmp/nixpkgs-branches'

function refresh_branches {
    git ls-remote --heads https://github.com/nixos/nixpkgs|awk '{print $2}'|grep -E 'refs/heads/nixos-[0-9.]+'|sed -e 's#refs/heads/nixos-\([0-9]*\.[0-9]*\).*#\1#'|uniq > $filename
}

if [[ ! -f $filename ]]; then
    refresh_branches
fi

if [[ $(find "$filename" -mtime +7 -print) ]]; then
    refresh_branches
fi

last=$(cat $filename | tail -n 1)
current=$(nix-channel --list --log-format internal-json|grep 'nixos-'|sed -e 's/.*nixos-\([0-9]*\.[0-9]*\).*/\1/')

if [[ $last != $current ]]; then
    echo "Last nixos release is $last and $current is found locally."
fi
