---
- hosts: all
  vars:
     home: /home/{{user}}/
     user: foo
     ansible_python_interpreter: /usr/bin/python2.7
  remote_user: root
  tasks:
     - name: "Clone Oh My ZSH from github"
       git:
          repo: "https://github.com/robbyrussell/oh-my-zsh"
          dest: "{{home}}/oh-my-zsh"
       become: yes
       become_user : "{{user}}"
     - name: "Clone Autosuggestions from github"
       git:
          repo: "https://github.com/zsh-users/zsh-autosuggestions"
          dest: "{{home}}/oh-my-zsh/custom/plugins/zsh-autosuggestions"
       become: yes
       become_user : "{{user}}"
     - name: "Clone Syntax from github"
       git:
          repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
          dest: "{{home}}/oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
       become: yes
       become_user : "{{user}}"
     - name: "Copy additionnal configuration files"
       copy:
        src:  "{{item}}"
        dest : "{{home}}/.{{item}}"
        owner: "{{user}}"
       with_items:
         - "screenrc"
         - "vimrc"
         - "nvimrc"
         - "bashrc"
         - "dircolors"
         - "zshenv"
     - name: "Link ZSH RC"
       file:
          src: "{{home}}/oh-my-zsh/templates/zshrc.zsh-template"
          dest: "{{home}}/.zshrc"
          state: "link"
          owner: "{{user}}"
     - name: "Create cache dirs"
       file:
          path: "{{home}}/{{item}}"
          state: "directory"
          owner: "{{user}}"
       with_items:
          - ".cache"
          - ".cache/zsh"
          - ".vimdat"
     - name: "Configure Oh My ZSH home dire"
       replace:
          path: "{{home}}/.zshrc"
          regexp: 'export ZSH=.*'
          replace: 'export ZSH="{{home}}/oh-my-zsh"'
     - name: "Configure Oh My ZSH prompt"
       replace:
          path: "{{home}}/.zshrc"
          regexp: 'ZSH_THEME=.*'
          replace: 'ZSH_THEME="cypher"'
     - name: "Configure Oh My ZSH plugins"
       replace:
          path: "{{home}}/.zshrc"
          regexp: 'plugins=.*'
          replace: 'plugins=(zsh-syntax-highlighting zsh-autosuggestions colored-man-pages)'
     - name: "Add waiting dots"
       replace:
          path: "{{home}}/.zshrc"
          regexp: '# COMPLETION_WAITING_DOTS="true"'
          replace: 'COMPLETION_WAITING_DOTS="true"'
     - name: "Add custom aliases and xports"
       lineinfile:
          path: "{{home}}/.zshrc"
          line: "{{item}}"
          state: "present"
       with_items:
          - "export EDITOR='vim'"
          - "export PAGER='less'"
          - "export LESS='-FSRXI'"
          - "unalias ll"
          - "ll (){/bin/ls -vFlq --color=yes --time-style=long-iso \"$@\" | sed \"s/$(date +%Y-%m-%d)/\x1b[32m     TODAY\x1b[m/;s/$(date +'%Y-%m-%d' -d yesterday)/\x1b[33m YESTERDAY\x1b[m/\"}"
          - "alias ls='/bin/ls --color=auto -F'"
          - "alias gitg='git log --graph --pretty=\"format:%ad %C(yellow)%h%Creset - %C(red)%an%Creset : %C(bold blue)%d%Creset %s\" --date=short'"
          - "alias gits='git status'"
          - "alias gitd='git diff'"


