---
- hosts: all
  vars:
     home: /home/{{user}}/
     user: foo
     ansible_python_interpreter: /usr/bin/python2.7
  remote_user: root
  tasks:
     - name: "Clone Oh My ZSH from github"
       git:
          repo: "https://github.com/robbyrussell/oh-my-zsh"
          dest: "{{home}}/oh-my-zsh"
       become: yes
       become_user : "{{user}}"
     - name: "Clone Autosuggestions from github"
       git:
          repo: "https://github.com/zsh-users/zsh-autosuggestions"
          dest: "{{home}}/oh-my-zsh/custom/plugins/zsh-autosuggestions"
       become: yes
       become_user : "{{user}}"
     - name: "Clone Syntax from github"
       git:
          repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
          dest: "{{home}}/oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
       become: yes
       become_user : "{{user}}"
     - name: "Create some directories"
       file:
          path: "{{home}}/{{item}}"
          state: "directory"
          owner: "{{user}}"
       with_items:
          - ".cache"
          - ".cache/zsh"
          - ".vimdat"
          - ".config/nvim/"
     - name: "Copy additionnal configuration files"
       copy:
        src:  "{{item.src}}"
        dest : "{{home}}/{{item.dst}}"
        owner: "{{user}}"
       with_items:
          - { src : "screenrc", dst : ".screenrc"}
          - { src : "vimrc", dst : ".vimrc"}
          - { src : "nvimrc", dst : ".config/nvim/init.vim"}
          - { src : "bashrc", dst : ".bashrc"}
          - { src : "dircolors", dst : ".dircolors"}
          - { src : "zshenv", dst : ".zshenv"}
          - { src : "emacs", dst : ".emacs"}
     - name: "Link ZSH RC"
       copy:
          src: "{{home}}/oh-my-zsh/templates/zshrc.zsh-template"
          dest: "{{home}}/.zshrc"
          owner: "{{user}}"
          remote_src: true
     - name: "Configure Oh My ZSH home dire"
       replace:
          dest: "{{home}}/.zshrc"
          regexp: 'export ZSH=.*'
          replace: 'export ZSH="{{home}}/oh-my-zsh"'
     - name: "Configure Oh My ZSH prompt"
       replace:
          dest: "{{home}}/.zshrc"
          regexp: 'ZSH_THEME=.*'
          replace: 'ZSH_THEME="cypher"'
     - name: "Configure Oh My ZSH plugins"
       shell: sed -i '/^plugins=(/,/)/{/^plugins=(/ s/.*/plugins=(zsh-syntax-highlighting zsh-autosuggestions colored-man-pages)/; t; d}' {{home}}/.zshrc
     - name: "Add waiting dots"
       replace:
          dest: "{{home}}/.zshrc"
          regexp: '# COMPLETION_WAITING_DOTS="true"'
          replace: 'COMPLETION_WAITING_DOTS="true"'
     - name: "Add custom aliases and xports"
       lineinfile:
          dest: "{{home}}/.zshrc"
          line: "{{item}}"
          state: "present"
       with_items:
          - "export EDITOR='vim'"
          - "export PAGER='less'"
          - "export LESS='-FSRXI'"
          - "unalias ll"
          - "ll (){/bin/ls -vFlq --color=yes --time-style=long-iso \"$@\" | sed \"s/$(date +%Y-%m-%d)/\x1b[32m     TODAY\x1b[m/;s/$(date +'%Y-%m-%d' -d yesterday)/\x1b[33m YESTERDAY\x1b[m/\"}"
          - "alias ls='/bin/ls --color=auto -F'"
          - "alias gitg='git log --graph --pretty=\"format:%ad %C(yellow)%h%Creset - %C(red)%an%Creset : %C(bold blue)%d%Creset %s\" --date=short'"
          - "alias gits='git status'"
          - "alias gitd='git diff'"
          - "alias gitw='git whatchanged'"


