---
- name: OS specific deployment - root phase
  hosts: localhost
  connection: local
  vars_files: host_vars/vault.yml
  tasks:
    - name: Install Linux stuff (Windows & MacOS are handled differently)
      ansible.builtin.include_role:
        name: os
      when: ansible_system == 'Linux'
    - name: Install Gentoo related stuff
      ansible.builtin.include_role:
        name: gentoo
      when: ansible_distribution == 'Gentoo'
    - name: Install debian related stuff
      ansible.builtin.include_role:
        name: debian
      when: ansible_distribution == 'Debian'
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
- name: OS specific deployment - user
  hosts: localhost
  connection: local
  vars_files: host_vars/vault.yml
  tasks:
    - name: Install gentoo user stuff
      ansible.builtin.include_role:
        name: gentoo_user
      when: ansible_distribution == 'Gentoo'
    - name: Install debian related stuff
      ansible.builtin.include_role:
        name: debian_user
      when: ansible_distribution == 'Debian'
