---
- name: OS specific deployment - root phase
  hosts: localhost
  connection: local
  tasks:
    - name: Install Linux stuff (Windows & MacOS are handled differently)
      ansible.builtin.include_role:
        name: os
      when: ansible_facts['system'] == 'Linux'

  become: true
  become_user: root
  become_method: ansible.builtin.sudo
