#!/usr/bin/env bash
set -e

function update_repo {
    BRANCH=${1:-master}
    git fetch
    git log $BRANCH..origin/$BRANCH --oneline --color|tee
    git rebase origin/$BRANCH
    git submodule update --init
}

update_repo $@
