---
- name: "User config"
  block:
    - name: "Check dependencies"
      command: "which {{ item }}"
      with_items:
         - go
         - ruby
         - pip
    - name: "Install share on desktop"
      template:
          src: "share.desktop"
          dest: "{{shares_dir}}/{{item.name}}.desktop"
          mode: 0755
      with_items: "{{shares}}"
    - name: "Clone additionnal repositories"
      git:
          repo: "{{item.repo}}"
          dest: "{{repos_dir}}/{{item.name}}"
      with_items: "{{repos}}"
      ignore_errors: yes
    - name: "Install gem dependencies"
      gem:
          name: "{{item}}"
          state: latest
      with_items: "{{ruby_gems}}"
    - name: "Install python dependencies"
      pip:
          name: "{{python_eggs}}"
          state: latest
          extra_args: "--user"
      when: nixos_file.stat.exists == false
    - name: "Install go dependencies"
      shell: "go get -u -v {{item}}"
      with_items: "{{go_bundles}}"
    - name: "Create Gentoo tooling" # Not to be put in Gentoo role as it's more user tooling than real OS conf
      template:
          src: gentools
          dest: "~/bin/"
          mode: 0755

  when: not minimal|bool
