---
- name: User config
  when: not minimal|bool
  block:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ shares_dir }}"
        state: directory
        mode: "0755"
    - name: Add TV Shortcut
      ansible.builtin.template:
        src: tv.j2
        dest: "{{ shares_dir }}/tv.desktop" # Shares dir is ok I guess
        mode: "0755"
    - name: Install share on desktop
      ansible.builtin.template:
        src: share.desktop
        dest: "{{ shares_dir }}/{{ item.name }}.desktop"
        mode: "0755"
      with_items: "{{ user_shares }}"
    - name: Ensure Thunar is default file browser
      xdg-mime:
        application: thunar.desktop
        mimetype: inode/directory
      when: ansible_system == "Linux"
    - name: Ensure Evince is default pdf viewer
      xdg-mime:
        application: org.gnome.Evince.desktop
        mimetype: application/pdf
      when: ansible_system == "Linux"
    - name: Ensure Loupe is default image viewer
      xdg-mime:
        application: org.gnome.Loupe.desktop
        mimetype: image/jpeg
      when: ansible_system == "Linux"
    - name: Clone additionnal user_repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ repos_dir }}/{{ item.name }}"
      with_items: "{{ user_repos }}"
      ignore_errors: true
    - name: User tooling not installed anymore
      ansible.builtin.debug:
        msg: Go (gopls) and Ruby (solargraph, rspec, pry, rubocop)
    - name: Create target directories for smount
      ansible.builtin.file:
        path: "{{ item.value.target }}"
        state: directory
        mode: "0755"
      with_items: "{{ user_smount_config.mounts | dict2items }}"
    - name: Put smount config
      ansible.builtin.copy:
        dest: ~/.smount/01personal
        content: "{{ user_smount_config | to_nice_yaml }}"
        mode: "0644"
