---
- name: "User config"
  block:
    - name: "Create directories"
      file:
        path: "{{shares_dir}}"
        state: "directory"
        mode: 0755
    - name: "Add TV Shortcut"
      template:
        src: tv.j2
        dest: "{{shares_dir}}/tv.desktop" # Shares dir is ok I guess
        mode: 0755
    - name: "Install share on desktop"
      template:
          src: "share.desktop"
          dest: "{{shares_dir}}/{{item.name}}.desktop"
          mode: 0755
      with_items: "{{shares}}"
    - name: "Ensure Thunar is default file browser"
      shell: "xdg-mime default thunar.desktop inode/directory"
    - name: "Clone additionnal repositories"
      git:
          repo: "{{item.repo}}"
          dest: "{{repos_dir}}/{{item.name}}"
      with_items: "{{repos}}"
      ignore_errors: yes
    - name: "Install gem dependencies"
      gem:
          name: "{{item}}"
          state: latest
          user_install: no # https://github.com/ansible/ansible/issues/50434
          norc: no
      with_items: "{{ruby_gems}}"
    - name: "Install go dependencies"
      shell: "go install -v {{item}}"
      with_items: "{{go_bundles}}"
    - name: "Create target directories for smount"
      file:
        path: "{{(item.values()|list|first)['target']}}"
        state: "directory"
        mode: 0755
      with_items: "{{smount_config.mounts}}"
    - name: "Put smount config"
      copy:
          dest: "~/.smount/01personal"
          content: "{{smount_config|to_nice_yaml}}"
          mode: 0644
  when: not minimal|bool
