#!/usr/bin/env python

import i3ipc
import sys
import os

if len(sys.argv) > 1 and sys.argv[1] == 'left':
    os.system("dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify " \
    "/org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause")
    sys.exit(0)


output = '🦆'
if len(i3ipc.Connection().get_tree().scratchpad().leaves()):
    output += ' 🐈'

print(output)
