---
exa_version: "0.9.0"
ls_cmd: "{{home}}/bin/exa-linux-x86_64 --git --icons"

# -S Chop long lines
# -R Print Raw control chars
# -F exit LESS if buffer fits in one screen
# -X Drop init
# -I Do case insensitive searches
# -W Highlight unread lines on scroll
lessopts: "-FSRXIW"

gitignore:
     - "TAGS"
     - ".DS_Store"
     - "Thumbs.db"
     - "*~"

# https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more
gitattributes:
    - "*.c     diff=cpp"
    - "*.c++   diff=cpp"
    - "*.cc    diff=cpp"
    - "*.cpp   diff=cpp"
    - "*.cs    diff=csharp"
    - "*.css   diff=css"
    - "*.el    diff=lisp"
    - "*.ex    diff=elixir"
    - "*.exs   diff=elixir"
    - "*.go    diff=golang"
    - "*.h     diff=cpp"
    - "*.h++   diff=cpp"
    - "*.hh    diff=cpp"
    - "*.hpp   diff=cpp"
    - "*.html  diff=html"
    - "*.js    diff=javascript"
    - "*.lisp  diff=lisp"
    - "*.m     diff=objc"
    - "*.md    diff=markdown"
    - "*.mm    diff=objc"
    - "*.php   diff=php"
    - "*.pl    diff=perl"
    - "*.py    diff=python"
    - "*.rake  diff=ruby"
    - "*.rb    diff=ruby"
    - "*.rs    diff=rust"
    - "*.ts    diff=javascript"
    - "*.xhtml diff=html"

cleanignore: ".dir-locals.el"

aliases:
    - "export EDITOR='vim'"
    - "export PAGER='less'"
    - "export LESS='{{ lessopts }}'"
    - "export ALTERNATE_EDITOR=''"
    - "alias ls='{{ls_cmd}} --color=auto -F'"
    - "alias cp='cp -iv'"
    - "alias mv='mv -iv'"
    - "alias ip='ip --color=auto'"
    - "alias gits='git status'"
    - "alias gitd='git diff'"
    - "alias gitg='git pull'"
    - "alias gitp='git push'"
    - "alias gitw='git whatchanged'"
    - "alias gitl='git tree'"
