---
- name: Install packages
  ansible.builtin.apt:
    package: "{{ item }}"
    state: present
  with_items: "{{ debian_packages }}"
- name: "Install delta from github"
  ansible.builtin.apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ debian_git_delta_version }}/git-delta_{{ debian_git_delta_version }}_amd64.deb"
    state: present
