---
- name: "Check dependencies"
  portage:
      package: "{{item}}"
      state: "present"
  with_items:
     - "app-portage/eix"
     - "app-portage/gentoolkit"
     - "app-portage/portpeek"
     - "app-portage/layman"
     - "app-portage/repoman"
     - "app-portage/genlop"
     - "app-portage/smart-live-rebuild"
     - "app-portage/cpuid2cpuflags"
     - "app-admin/eclean-kernel"
     - "app-portage/portage-utils"
     - "app-forensics/chkrootkit"
     - "dev-python/pip"
     - "dev-lang/ruby"
     - "dev-lang/go"
- name: "Copy eix config"
  copy:
      src: "00-eixrc"
      dest: "/etc/eixrc/"
      mode: 0644
- name: "Copy eix exec in portage"
  copy:
      src: "eix"
      dest: "/etc/portage/repo.postsync.d/"
      mode: 0755
- name: "Copy localrepo config"
  template:
      src: "localrepo.conf"
      dest: "/etc/portage/repos.conf/"
      mode: 0644
- name: "Create localrepo dir"
  file:
      path: "{{item}}"
      state: directory
  with_items:
      - "{{localrepo}}"
      - "{{localrepo}}/metadata"
      - "{{localrepo}}/profiles"
- name: "Create metadata for localrepo"
  copy:
      dest: "{{localrepo}}/metadata/"
      src: "layout.conf"
- name: "Create repo_name for localrepo"
  copy:
      dest: "{{localrepo}}/profiles/repo_name"
      content: "localrepo\n"
- name: "Add memo in root folder"
  get_url:
      url: "https://gist.githubusercontent.com/Lqp1/bf109ab5a6aa7e987603d00b0011e1ea/raw/7bfa98a36cdafc7e30d6c5b6a617eb0ebd334646/gentoo-notes.md"
      dest: "/root/memo.md"
- name: "Register CPU flags"
  command: "cpuid2cpuflags"
  register: flags
- name: "Setup CPU flags as use flags"
  template:
      src: "00cpu-flags.j2"
      dest: "/etc/portage/package.use/00cpu-flags"
- name: "Ensure we build binary package, and use it as much as possible"
  lineinfile:
      path: "/etc/portage/make.conf"
      line: 'FEATURES="buildpkg getbinpkg"'
