---
- name: "Check dependencies"
  portage:
      package: "{{item}}"
      state: "present"
  with_items:
     - "app-portage/eix"
     - "app-portage/gentoolkit"
     - "app-portage/layman"
     - "app-portage/repoman"
     - "app-portage/cpuid2cpuflags"
- name: "Copy eix config"
  copy:
      src: "00-eixrc"
      dest: "/etc/eixrc/"
      mode: 0644
- name: "Copy eix exec in portage"
  copy:
      src: "eix"
      dest: "/etc/portage/repo.postsync.d/"
      mode: 0755
- name: "Copy localrepo config"
  template:
      src: "localrepo.conf"
      dest: "/etc/portage/repos.conf/"
      mode: 0644
- name: "Copy personal overlay config"
  template:
      src: "overlay.conf"
      dest: "/etc/portage/repos.conf/lqp1.conf"
      mode: 0644
- name: "Create localrepo dir"
  file:
      path: "{{item}}"
      state: directory
  with_items:
      - "{{localrepo}}"
      - "{{localrepo}}/metadata"
      - "{{localrepo}}/profiles"
- name: "Create metadata for localrepo"
  copy:
      dest: "{{localrepo}}/metadata/"
      src: "layout.conf"
      mode: 0644
- name: "Create repo_name for localrepo"
  copy:
      dest: "{{localrepo}}/profiles/repo_name"
      content: "localrepo\n"
      mode: 0644
- name: "Add memo in root folder"
  get_url:
      url: "https://gist.githubusercontent.com/Lqp1/bf109ab5a6aa7e987603d00b0011e1ea/raw/gentoo-notes.md"
      dest: "/root/memo.md"
- name: "Register CPU flags"
  command: "cpuid2cpuflags"
  register: flags
- name: "Setup CPU flags as use flags"
  template:
      src: "00cpu-flags.j2"
      dest: "/etc/portage/package.use/00cpu-flags"
      mode: 0644
- name: "Ensure we build binary package, and use it as much as possible"
  lineinfile:
      path: "/etc/portage/make.conf"
      regexp: 'FEATURES=.*'
      line: 'FEATURES="buildpkg"'
- name: "Ensure sane defaults for emerge"
  lineinfile:
      path: "/etc/portage/make.conf"
      regexp: 'EMERGE_DEFAULT_OPTS=.*'
      line: 'EMERGE_DEFAULT_OPTS="--ask-enter-invalid --binpkg-changed-deps=y --binpkg-respect-use=y --read-news --oneshot --verbose-conflicts --quiet-build --getbinpkg=y"'
- name: "Setup personal use flags (hardware agnostic)"
  copy:
      src: "01personal"
      dest: "/etc/portage/package.use/01personal"
      mode: 0644
- name: "Setup accepted keywords"
  copy:
      dest: "/etc/portage/package.accept_keywords/01personal"
      content: "{{gentoo_accepted_unstable | join(' ~amd64\n')}} ~amd64\n"
      mode: 0644
- name: "Setup accepted licenses"
  copy:
      dest: "/etc/portage/package.license/01personal"
      content: "{{gentoo_accepted_licenses | join(' \n')}}\n"
      mode: 0644
- name: "Blacklist some modules"
  copy:
      dest: "/etc/modprobe.d/{{item}}.conf"
      content: "blacklist {{item}}\n"
      mode: 0644
  with_items:
      - 'pcspkr'
      - 'snd_pcsp'
- name: "Setup sudoers rules"
  copy:
      dest: "/etc/sudoers.d/ansible"
      src: "sudoers"
      mode: 0440
- name: "Ensure set directory exists"
  file:
      path: "/etc/portage/sets/"
      state: directory
- name: "Setup sets/personal package set"
  copy:
      dest: "/etc/portage/sets/personal"
      content: "{{gentoo_packages | join(' \n')}}\n"
      mode: 0644
