#!/usr/bin/env bash
#vim: set ft=sh:


# rclone needs to be setup beforehands
SYNC_CMD="sudo rclone"

# Push local content in the remote
# Deletes non existent binpkgs as they would not be present in metadata file
if [ "$1" = "push_packages" ]
then
    $SYNC_CMD sync -P /var/cache/binpkgs gentoo:/gentoo/binpkgs
fi

if [ "$1" = "diff_packages" ]
then
    $SYNC_CMD copy gentoo:/gentoo/binpkgs/Packages /tmp
    vimdiff /tmp/Packages /var/cache/binpkgs/Packages
fi

# Get remote files, put them locally, then rebuild metadata
# Can be used for local install, or to push afterwards with newly built packages
if [ "$1" = "pull_packages" ]
then
    $SYNC_CMD copy -P gentoo:/gentoo/binpkgs /var/cache/binpkgs
    sudo emaint binhost --fix
fi
