" VIMRC

" Global settings
set nocompatible
set cursorline
set history=100
set hidden
set timeoutlen=200
set lazyredraw
set sessionoptions=buffers,folds
filetype plugin on
filetype indent on
"autocmd BufEnter * if &buftype == "" && isdirectory(expand('%:p:h'))| cd %:p:h | endif
set backspace=indent,eol,start

" Set cursor to last known position
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Encoding
set encoding=utf8
set ffs=unix,dos,mac

" Avoid conflicts; re-read changed files
set autoread

" Set Leader key to Space and add several shortcuts
let mapleader=" "
nnoremap <silent> <Leader><Tab> :b#<CR>
nnoremap <silent> <Leader>n :bnext<CR>
nnoremap <silent> <Leader>b :ls<CR>
nnoremap <silent> <Leader>d :bdelete<CR>
nnoremap <Leader><Leader> :

" Shortcut to sudo-save a file
command W :execute ':silent w !sudo tee % > /dev/null' | :edit!

" Auto-save sessions
"autocmd VimLeave * mksession! ~/.vimdat/session.vim
"autocmd VimEnter * silent! source ~/.vimdat/session.vim | silent! edit #

" Shortcut to exit insert mode faster
inoremap jk <ESC>
if has("terminal")
    tnoremap jk <C-\><C-n>
end

" Indent and dev and tabs
syntax on
set smartindent
set autoindent
set shiftwidth=4
filetype on
set showmatch
set mat=4
set smarttab
set tabstop=4
set softtabstop=4
set expandtab
if has("colorcolumn")
    set cc=+80
end
augroup tabs
    autocmd!
    autocmd FileType make,go setlocal noexpandtab
augroup end


" Status line
set laststatus=2
set statusline=%1*%m%*%r%h\ %2*%f%*\ [%{strlen(&fenc)?&fenc:'none'},%{&ff},%{strlen(&ft)?&ft:'none'}]%=%c,%l/%L
augroup statusline
    autocmd!
    autocmd InsertEnter * hi StatusLine ctermfg=70
    autocmd InsertLeave * hi StatusLine ctermfg=189
augroup end

" Backup
if !isdirectory($HOME . "/.vimdat")
    call mkdir($HOME . "/.vimdat/backups", "p", 0700)
    call mkdir($HOME . "/.vimdat/swaps", "p", 0700)
    call mkdir($HOME . "/.vimdat/undos", "p", 0700)
endif
set backup
set udf
set backupdir=~/.vimdat/backups
set dir=~/.vimdat/swaps
set udir=~/.vimdat/undos

" Search tips
set wrapscan
set hlsearch
set ignorecase
set smartcase
set incsearch

" Concealing
set conceallevel=2

" Spelling tips
augroup textfiles
    autocmd!
    autocmd BufEnter *.txt,README,*.md set spell textwidth=80
    autocmd BufEnter *.txt,README,*.md syntax match arrow "->" conceal cchar=→
augroup end

" Show line number
set number relativenumber
highlight LineNr term=bold ctermfg=darkgray guifg=darkgray

" Highlight trailing Tabs, Spaces and special chars
augroup specialchars
    autocmd!
    autocmd Colorscheme * highlight Tab ctermbg=darkgray guibg=darkgray
    autocmd Colorscheme * highlight Space ctermbg=darkblue guibg=darkblue
    autocmd Colorscheme * highlight nonAscii ctermfg=blue guifg=blue
    autocmd BufWinEnter * let w:m2=matchadd('Tab', '\t', -1)
    autocmd BufWinEnter * let w:m3=matchadd('Space', '\s\+$\| \+\ze\t', -1)
    autocmd BufWinEnter *.txt,README,*.md let w:m4=matchadd('nonAscii', '[^\d0-\d127]', -1)
augroup end

" Use 256 colors
set t_Co=256

" Allow mouse and system clipboard smoothly
set mouse=a
set clipboard=unnamedplus

" Misc
set wildmode=longest,list,full
set wildmenu
set path+=**
set showcmd
imap <C-d> <C-o>daw

" Folding
set foldmethod=syntax
set foldlevel=20

" NetRW config
let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3

" Modeline
ab MODELINE vim: set ts=4 sw=4 ai ff=unix:
" set modeline

" Local VIMRC
if filereadable(expand("~/.vim_local"))
    source ~/.vim_local
endif

" Theming
silent! colorscheme solarized
highlight Comment cterm=italic
