---
localrepo: "/var/db/repos/localrepo"
personaloverlay: "/var/db/repos/lqp1/"
gentoo_remote_host: ""
gentoo_bin_uri: "{% if gentoo_remote_host != '' %}rsync://{{gentoo_remote_host}}/gentoo/binpkgs/{% endif %}"

gentoo_features:
  - "buildpkg"
  - "strict"
  - "collision-protect"
  - "parallel-install"
  - "cgroup"
  - "ipc-sandbox"

gentoo_systemd_services:
    - "acpid"
    - "bluetooth"
    - "clamav-daemon"
    - "clamav-freshclam"
    - "cronie"
    - "cups"
    - "iptables-restore"
    - "ip6tables-restore"
    - "laptop-mode"
    - "pcscd"
    - "sddm"
    - "thermald"
    - "rtkit-daemon"

gentoo_accepted_unstable:
    - "app-crypt/veracrypt"
    - "app-text/vgrep" # to replace ag
    - "media-fonts/quivira"
    - "net-wireless/blueman"
    - "media-gfx/sane-airscan"
    - "x11-misc/miraclecast"
    - "x11-terms/kitty"
    - "x11-terms/kitty-terminfo"
    - "x11-terms/kitty-shell-integration"
    - "sys-apps/gentoo-changelog-tracker"
    - "sys-apps/bat"
gentoo_accepted_all:
    - "sys-apps/smount"
gentoo_accepted_licenses:
    - "sys-kernel/linux-firmware @BINARY-REDISTRIBUTABLE"
    - "sys-firmware/intel-microcode intel-ucode"
    - "app-crypt/veracrypt truecrypt-3.0"
    - ">=media-fonts/corefonts-1-r7 MSttfEULA"
    - "x11-libs/libva-intel-media-driver no-source-code"
    - ">=sys-firmware/alsa-firmware-1.2.4-r1 freedist all-rights-reserved"

gentoo_packages:
    - "app-admin/ccze"
    - "app-admin/eclean-kernel"
    - "app-admin/keepassxc"
    - "app-admin/sudo"
    - "app-antivirus/clamav"
    - "app-antivirus/clamtk"
    - "app-arch/p7zip"
    - "app-arch/unzip"
    - "app-crypt/veracrypt"
    - "app-crypt/ccid"
    - "app-editors/emacs"
    - "app-editors/vim"
    - "app-forensics/chkrootkit"
    - "app-misc/screen"
    - "app-portage/genlop"
    - "app-portage/portage-utils"
    - "app-portage/portpeek"
    - "app-portage/smart-live-rebuild"
    - "app-shells/autojump"
    - "app-shells/zsh"
    - "app-text/evince"
    - "app-text/tree"
    - "app-text/vgrep"
    - "dev-java/openjdk-bin"
    - "dev-lang/go"
    - "dev-lang/ruby"
    - "dev-libs/libcgroup"
    - "dev-lisp/sbcl"
    - "dev-python/ipython"
    - "dev-python/pip"
    - "dev-util/android-tools"
    - "dev-util/ctags"
    - "dev-util/git-delta"
    - "dev-vcs/tig"
    - "media-gfx/sane-backends"
    - "media-gfx/sane-airscan"
    - "media-plugins/alsa-plugins"
    - "media-sound/alsa-utils"
    - "media-sound/pavucontrol"
    - "media-video/vlc"
    - "net-analyzer/iftop"
    - "net-analyzer/iptraf-ng"
    - "net-fs/samba"
    - "net-fs/sshfs"
    - "net-misc/rclone"
    - "net-misc/httpie"
    - "net-p2p/transmission"
    - "net-print/cups"
    - "net-print/hplip"
    - "net-wireless/blueman"
    - "sys-apps/bat"
    - "sys-apps/firejail"
    - "sys-apps/fwupd"
    - "sys-apps/gentoo-changelog-tracker"
    - "sys-apps/gsmartcontrol"
    - "sys-apps/hdparm"
    - "sys-apps/lm-sensors"
    - "sys-apps/lshw"
    - "sys-apps/moreutils"
    - "sys-apps/pciutils"
    - "sys-apps/pcsc-tools"
    - "sys-apps/smount"
    - "sys-apps/ripgrep"
    - "sys-apps/usbutils"
    - "sys-auth/rtkit"
    - "sys-process/lsof"
    - "sys-process/cronie"
    - "sys-fs/dfc"
    - "sys-fs/dosfstools"
    - "sys-fs/e2fsprogs"
    - "sys-fs/exfat-utils"
    - "sys-fs/fuse-exfat"
    - "sys-fs/mtpfs"
    - "sys-fs/ntfs3g"
    - "sys-power/powertop"
    - "sys-power/thermald"
    - "sys-process/htop"
    - "sys-process/iotop"

gentoo_packages_X11:
    - "app-arch/file-roller"
    - "app-office/libreoffice-bin"
    - "app-office/libreoffice-l10n"
    - "gnome-extra/nm-applet"
    - "media-fonts/corefonts"
    - "media-fonts/dejavu"
    - "media-fonts/droid"
    - "media-fonts/fira-code"
    - "media-fonts/noto"
    - "media-fonts/noto-emoji"
    - "media-fonts/quivira"
    - "media-gfx/feh"
    - "media-gfx/gimp"
    - "media-gfx/ristretto"
    - "media-sound/audacity"
    - "sys-block/gparted"
    - "sys-power/acpilight"
    - "www-client/firefox-bin"
    - "x11-base/xorg-server"
    - "x11-misc/arandr"
    - "x11-misc/dunst"
    - "x11-misc/i3lock"
    - "x11-misc/picom"
    - "x11-misc/polybar"
    - "x11-misc/redshift"
    - "x11-misc/rofi"
    - "x11-misc/sddm"
    - "x11-misc/xclip"
    - "x11-misc/xdotool"
    - "x11-misc/xss-lock"
    - "x11-terms/kitty"
    - "x11-themes/arc-icon-theme"
    - "x11-themes/arc-theme"
    - "x11-wm/i3"
    - "xfce-extra/thunar-archive-plugin"
    - "xfce-extra/thunar-shares-plugin"
    - "xfce-extra/thunar-volman"
    - "xfce-extra/tumbler"
    - "xfce-extra/xfce4-clipman-plugin"
    - "xfce-extra/xfce4-screenshooter"

gentoo_packages_laptop:
    - "app-laptop/laptop-mode-tools"
