---
localrepo: "/var/db/repos/localrepo"
personaloverlay: "/var/db/repos/lqp1/"
gentoo_accepted_unstable:
    - "app-crypt/veracrypt"
    - "app-text/vgrep" # to replace ag
    - "media-fonts/quivira"
    - "net-wireless/blueman"
    - "x11-misc/miraclecast"
    - "x11-terms/kitty"
    - "x11-terms/kitty-terminfo"
gentoo_accepted_licenses:
    - "sys-kernel/linux-firmware @BINARY-REDISTRIBUTABLE"
    - "sys-firmware/intel-microcode intel-ucode"
    - "app-crypt/veracrypt truecrypt-3.0"
    - ">=media-fonts/corefonts-1-r7 MSttfEULA"
gentoo_packages:
    - "app-admin/ccze"
    - "app-admin/eclean-kernel"
    - "app-admin/keepassxc"
    - "app-admin/sudo"
    - "app-antivirus/clamav"
    - "app-arch/p7zip"
    - "app-arch/unzip"
    - "app-crypt/veracrypt"
    - "app-editors/emacs"
    - "app-editors/vim"
    - "app-forensics/chkrootkit"
    - "app-misc/screen"
    - "app-portage/genlop"
    - "app-portage/portage-utils"
    - "app-portage/portpeek"
    - "app-portage/smart-live-rebuild"
    - "app-shells/autojump"
    - "app-shells/zsh"
    - "app-text/evince"
    - "app-text/tree"
    - "app-text/vgrep"
    - "dev-java/openjdk-bin"
    - "dev-lang/go"
    - "dev-lang/ruby"
    - "dev-libs/libcgroup"
    - "dev-lisp/sbcl"
    - "dev-python/ipython"
    - "dev-python/pip"
    - "dev-util/android-tools"
    - "dev-util/ctags"
    - "media-plugins/alsa-plugins"
    - "media-sound/alsa-utils"
    - "media-sound/pavucontrol"
    - "media-video/vlc"
    - "net-analyzer/iftop"
    - "net-fs/samba"
    - "net-fs/sshfs"
    - "net-misc/rclone"
    - "net-p2p/transmission"
    - "net-print/hplip"
    - "net-wireless/blueman"
    - "sys-apps/gsmartcontrol"
    - "sys-apps/hdparm"
    - "sys-apps/lm-sensors"
    - "sys-apps/lshw"
    - "sys-apps/moreutils"
    - "sys-apps/pciutils"
    - "sys-apps/the_silver_searcher"
    - "sys-apps/usbutils"
    - "sys-fs/dfc"
    - "sys-fs/dosfstools"
    - "sys-fs/exfat-utils"
    - "sys-fs/fuse-exfat"
    - "sys-fs/mtpfs"
    - "sys-fs/ntfs3g"
    - "sys-power/powertop"
    - "sys-process/htop"
    - "sys-process/iotop"

gentoo_packages_X11:
    - "app-arch/file-roller"
    - "app-office/libreoffice-bin"
    - "app-office/libreoffice-l10n"
    - "gnome-extra/nm-applet"
    - "media-fonts/corefonts"
    - "media-fonts/dejavu"
    - "media-fonts/droid"
    - "media-fonts/noto"
    - "media-fonts/noto-emoji"
    - "media-fonts/quivira"
    - "media-gfx/feh"
    - "media-gfx/gimp"
    - "media-gfx/ristretto"
    - "sys-block/gparted"
    - "www-client/firefox-bin"
    - "x11-base/xorg-server"
    - "x11-misc/arandr"
    - "x11-misc/polybar"
    - "x11-misc/redshift"
    - "x11-misc/rofi"
    - "x11-misc/slim"
    - "x11-misc/xclip"
    - "x11-misc/xdotool"
    - "x11-terms/kitty"
    - "x11-themes/arc-icon-theme"
    - "x11-themes/arc-theme"
    - "x11-wm/i3"
    - "xfce-base/xfce4-meta"
    - "xfce-extra/thunar-archive-plugin"
    - "xfce-extra/thunar-shares-plugin"
    - "xfce-extra/thunar-volman"
    - "xfce-extra/tumbler"
    - "xfce-extra/xfce4-notifyd"
    - "xfce-extra/xfce4-power-manager"
    - "xfce-extra/xfce4-screenshooter"
