---
- name: Install nix
  when: not minimal|bool
  block:

    - name: Create some directories
      ansible.builtin.file:
        path: ~/.profile.d/
        state: directory
        mode: "0755"
    - name: Setup nix and hm variables in profiles
      ansible.builtin.template:
        src: env
        dest: ~/.profile.d/20nix
        mode: "0644"

    - name: Update channels
      ansible.builtin.command: nix-channel --update
      changed_when: true
    - name: Create local app directory
      ansible.builtin.file:
        path: ~/.local/share/applications/
        state: directory
        mode: "0755"

    - name: Create /bin dir to store test script
      ansible.builtin.file:
        path: ~/bin
        state: directory
        mode: "0755"
    - name: Copy nix release script in binary directory
      ansible.builtin.copy:
        src: haz-nix-release
        dest: "~/bin/haz-nix-release"
        mode: "0755"
    - name: Test if a new Nix channel release is found
      ansible.builtin.command: ~/bin/haz-nix-release
      register: nix_releases
      changed_when: false
    - name: Warn if a newer Nix channel is found
      ansible.builtin.fail:
        msg: "Warning: New release of Nix channel detected: {{ nix_releases.stdout }}"
      when: nix_releases.stdout != "" and ansible_facts['system'] == "Darwin"
      ignore_errors: true
      changed_when: false
