---
- name: Install nix
  when: not minimal|bool
  block:

    - name: Create some directories
      ansible.builtin.file:
        path: ~/.profile.d/
        state: directory
        mode: "0755"
    - name: Setup nix and hm variables in profiles
      ansible.builtin.template:
        src: env
        dest: ~/.profile.d/20nix
        mode: "0644"

    - name: Remove stale nix release script
      ansible.builtin.file:
        path: ~/bin/haz-nix-release
        state: absent
