---
- name: Change defaults for root user
  ansible.builtin.set_fact:
    home: /root
    minimal: true
    common_ls_cmd: ls
  when: ansible_user_id == 'root'

- name: Minimal
  ansible.builtin.debug:
    var: minimal

- name: Check is host is NixOS
  ansible.builtin.stat:
    path: /etc/NIXOS
  register: nixos_file
