---
debian_packages:
  # - "cronie"
  # - "lazygit"
  # - "veracrypt"
  - 7zip
  - autojump
  - bat
  - btop
  - ccze
  - dfc
  - feh
  - fwupd
  - golang
  - gsmartcontrol
  - hdparm
  - hplip
  - htop
  - httpie
  - iftop
  - iotop
  - iptraf-ng
  - keepassxc
  - kitty
  - lm-sensors
  - lshw
  - lsof
  - moreutils
  - pciutils
  - pcsc-tools
  - pipx
  - powertop
  - pylint
  - python3-autopep8
  - python3-flake8
  - python3-ipdb
  - python3-ipython
  - python3-pip
  - rclone
  - ripgrep
  - rtkit
  - ruby
  - sbcl
  - screen
  - sshfs
  - sudo
  - thermald
  - tig
  - tree
  - unzip
  - usbutils
  - vim
  - xclip
  - xdotool
  - zsh

      # - "app-antivirus/clamav"
      # - "app-antivirus/clamtk"
      # - "app-arch/file-roller"
      # - "app-crypt/ccid"
      # - "app-forensics/chkrootkit"
      # - "app-laptop/laptop-mode-tools"
      # - "app-office/libreoffice-bin"
      # - "app-office/libreoffice-l10n"
      # - "app-shells/zsh-completions"
      # - "app-text/evince"
      # - "dev-java/openjdk-bin"
      # - "dev-libs/libcgroup"
      # - "dev-python/python-lsp-server"
      # - "dev-python/pyyaml"
      # - "dev-util/android-tools"
      # - "dev-util/ctags"
      # - "gnome-extra/nm-applet"
      # - "media-fonts/corefonts"
      # - "media-fonts/dejavu"
      # - "media-fonts/droid"
      # - "media-fonts/fira-code"
      # - "media-fonts/noto"
      # - "media-fonts/noto-emoji"
      # - "media-fonts/quivira"
      # - "media-gfx/gimp"
      # - "media-gfx/ristretto"
      # - "media-gfx/sane-airscan"
      # - "media-gfx/sane-backends"
      # - "media-plugins/alsa-plugins"
      # - "media-sound/alsa-utils"
      # - "media-sound/audacity"
      # - "media-sound/pavucontrol"
      # - "media-video/pipewire"
      # - "media-video/vlc"
      # - "net-fs/samba"
      # - "net-p2p/transmission"
      # - "net-print/cups-meta"
      # - "net-print/hplip"
      # - "net-wireless/blueman"
      # - "sys-apps/firejail"
      # - "smount"
      # - "sys-block/gparted"
      # - "sys-fs/dosfstools"
      # - "sys-fs/e2fsprogs"
      # - "sys-fs/exfat-utils"
      # - "sys-fs/fuse-exfat"
      # - "sys-fs/mtpfs"
      # - "sys-fs/ntfs3g"
      # - "sys-power/acpilight"
      # - "www-client/firefox-bin"
      # - "x11-apps/igt-gpu-tools"
      # - "x11-base/xorg-server"
      # - "x11-misc/arandr"
      # - "x11-misc/autotiling"
      # - "x11-misc/dunst"
      # - "x11-misc/i3lock"
      # - "x11-misc/picom"
      # - "x11-misc/polybar"
      # - "x11-misc/redshift"
      # - "x11-misc/rofi"
      # - "x11-misc/rofimoji"
      # - "x11-misc/sddm"
      # - "x11-misc/xss-lock"
      # - "x11-terms/kitty"
      # - "x11-themes/arc-icon-theme"
      # - "x11-themes/arc-theme"
      # - "x11-wm/i3"
      # - "xfce-base/thunar-volman"
      # - "xfce-base/tumbler"
      # - "xfce-extra/thunar-archive-plugin"
      # - "xfce-extra/thunar-user_shares-plugin"
      # - "xfce-extra/xfce4-clipman-plugin"
      # - "xfce-extra/xfce4-screenshooter"
