---
repos:
    - repo: https://github.com/powerline/fonts.git
      name: powerline-fonts
    - repo: https://github.com/speed47/spectre-meltdown-checker
      name: spectre-meltdown-checker
    - repo: https://github.com/stove-panini/fontconfig-emoji
      name: fontconfig-emoji
    - repo: https://github.com/a13xp0p0v/kconfig-hardened-check
      name: kconfig-hardened-check

ruby_gems:
      - bundler
      - pry
      - rubocop
      - rspec
      - solargraph

python_eggs:
      - python-language-server
      - pyls-isort
      - pyls-mypy
      - pyls-black
      - flake8
      - autoflake
      - ipython

go_bundles:
      - "golang.org/x/tools/gopls"
      - "github.com/godoctor/godoctor"
      - "github.com/rogpeppe/godef"

shares:
    - name: Assurancetourix
      ip: 192.168.1.5
    - name: Obelix
      ip: 192.168.1.2
