---
repos:
    - repo: https://github.com/powerline/fonts.git
      name: powerline-fonts
    - repo: https://github.com/speed47/spectre-meltdown-checker
      name: spectre-meltdown-checker
shares:
    - name: Assurancetourix
      ip: 192.168.1.5
    - name: Obelix
      ip: 192.168.1.2
shares_dir: "{{home}}/Bureau/"
repos_dir: "{{home}}/Documents/Repo/"
